language: python

notifications:
  email:
        - jkmtravisnotify@gmail.com

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt

script:
  - pytest distrib-dyn-modeling/sabaody
